# Generated by Django 3.2.7 on 2022-03-20 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='deployment id', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('s', 'Success'), ('e', 'Error'), ('u', 'Unknown')], default='u', help_text='Project DEPLOYMENT_STATUS status', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='project.projectstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
